### ISSUE TITLE
Noob problem

### ISSUE THREAD

**Issue by rgomensoro** [expo/create-react-native-app#842]
Hi Guys,

Iḿ very new on react native.

I'm trying to load a first react-native app, from create-react-native-app, but keep on loading (top green message) or didn't  show anything (only the draw of circles inside a dotted square).

probably is something very dummy.

It is the very simple created with:
`export default function App() {
  return (
    <View style={styles.container}>
      <Text>Test App - First React Native App!</Text>
      <StatusBar style="auto" />
    </View>
  );
}
`

only this view in App.js.

I'm on Ubuntu 18.04.
node is v14
all version is up-to-date 

Sorry to bother you with this dummy/noob problem.

**Comment by byCedric** [comment]
Hi @rgomensoro! I'm not sure if this is the right repository to ask this question 😄  You might find more luck in the [React Native Help section of the docs](https://reactnative.dev/en/help). It shows you where you can get help for certain types of problems. If you think there might be something wrong, and want to open an issue somewhere, it would help to include a screenshot of what you are seeing. I'm not 100% what you mean by the description you provided. For now, I'll close this issue because this repository mainly focuses on the install tool itself.

Hope it helps!

PS. don't say sorry for questions you might have! If you tried fixing or researching the issue, you put in some effort. As long as you did that, you can ask for help in the right channels (e.g. forums or slack communities)
