### ISSUE TITLE
npx create-expo-app@latest --template tabs@sdk-49 but without typescript

### ISSUE THREAD

**Issue by halid96** [expo/create-react-native-app#926]
npx create-expo-app@latest --template blank@sdk-49

creates a TypeScript project... why prioritize TypeScript over Javascript? 😀 Wouldn't be cool if we had a tabs template but with JavaScript... 🤔

**Comment by talbertherndon** [comment]
i agree

**Comment by talbertherndon** [comment]
i create a js version of the template it works exactly the same:

https://github.com/talbertherndon/expo-tabs-sdk50-js

**Comment by marklawlor** [comment]
This is unlikely to happen. We want to maintain only a small number of templates, and having duplicate JS/TS templates defeats that purpose. Templates serve both as quick-starters and as demonstrations of the major features of Expo Router, some of which rely on TypeScript.

For instance, most router libraries implement some form of dead link detection, and for a while, this was the most requested feature for Expo Router. In version 2, we introduced TypeScript types for your links. Consequently, your TypeScript build will fail if a dead link is detected because the link no longer matches a valid type.

I'm not saying you should use TS or JS. I'm just saying that we have some features which are TS only, hence why the template is TS.
